server:
  port: 8081
spring:
  application:
    name: spring-security-oauth2-client
  thymeleaf:
    encoding: UTF-8
  security:
    oauth2:
      client:
        registration:
          springMvcClient:
            provider: identityserver4
            client-id: springMvc
            client-secret: secret
            authorization-grant-type: authorization_code
            scope: openid,profile,apiBook.read
        provider:
          identityserver4:
            issuer-uri: http://localhost:5001
logging:
  level:
    root: INFO
restApi: http://localhost:8080/api/v1
pageSize: 5
